version: "3"
services:
  # dbt:
  #   container_name: dbt
  #   image: ghcr.io/dbt-labs/dbt-postgres:latest
  #   working_dir: /root/dbt_project
  #   environment:
  #     DBT_PROFILES_DIR: /root/dbt_project
  #   volumes:
  #     - ./dbt_project:/root/dbt_project
  #   #    command: ["debug", "--config-dir"]
  #   command: ["run"]
  #   depends_on:
  #     - postgres
  #   networks:
  #     - dbt_network

  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      - dbt_network
      - db_network
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/sources.sql:/docker-entrypoint-initdb.d/init.sql

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - db_network
    depends_on:
      - postgres

networks:
  dbt_network:
    driver: bridge
  db_network:
    driver: bridge

volumes:
  pgdata:
