prototype:
  target: docker
  outputs:
    docker:
      type: postgres
      host: postgres
      port: 5432
      user: myuser
      pass: mypassword
      dbname: mydb
      schema: public

    local:
      type: postgres
      host: localhost
      port: 5432
      user: myuser
      pass: mypassword
      dbname: mydb
      schema: public
