airport_flights:
  target: local
  outputs:
    docker:
      type: postgres
      host: postgres
      port: 5432
      user: user
      pass: password
      dbname: postgres

    local:
      type: postgres
      host: localhost
      port: 5432
      user: user
      pass: password
      dbname: postgres
